### ISSUE TITLE
a small mistake in the document

### ISSUE THREAD

**Issue by AKA-Able** [RoaLogic/ahb3lite_interconnect#18]
In the document,the signal mst_HRESP of master port is described ‘input’， but it should be 'output'.
![~64{RK5(828P LT} KOS{F4](https://user-images.githubusercontent.com/48235749/229517295-b02ca1ae-be11-4159-a542-49b2fbd125b8.png)
![A _JXX67BVG54((RY2RMG6W](https://user-images.githubusercontent.com/48235749/229517307-cde74ec8-f2fd-4786-be0d-bd96565664ba.png)

**Comment by rherveille** [comment]
Fixed in tex sources. HTML and PDF need regeneration

**Comment by rherveille** [comment]
Fixed in all documentation
